package com.example.firstApi.enums;

public enum PermissionEnum {
    UPDATE_MY_INFORMATIONS,
    CREATE_ADMIN,
    INACTIVATE_CUSTOMER,
    SELECT_CUSTOMER,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    SELECT_PRODUCT,
    SELECT_PRODUCTS,
    CREATE_ORDER,
    SELECT_MY_ORDERS,
    SELECT_CUSTOMER_ORDERS,
    SELECT_MY_ORDER,
    SELECT_CUSTOMER_ORDER,

}
